spring.application.name=movie-service
spring.datasource.url=jdbc:mysql://comp713-s2-2026.c5m2mi6uava2.ap-southeast-2.rds.amazonaws.com:3306/comp713_17988896
spring.datasource.username=comp713_17988896
spring.datasource.password=dXK!Ht-Rzpgz%y-r2YABbHSX

spring.jpa.hibernate.ddl-auto=update

server.port=${SERVER_PORT:8083}

management.endpoint.health.show-details=never