spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://comp713-s2-2026.c5m2mi6uava2.ap-southeast-2.rds.amazonaws.com:3306/comp713_17988896
    username: c713_17988896
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8083}

management:
  endpoint:
    health:
      show-details: never