--seed data for movie showing table
--INSERT IGNORE so it doesn't throw an exception as every time the service runs it will try and
--insert the same rows

--There are 5 movies showing from the 21st of september to the 30th of september everyday, the
--showtimes are only at 12pm and 5pm

INSERT IGNORE INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-21', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-21', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-22', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-22', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-23', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-23', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-24', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-24', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-25', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-25', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-26', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-26', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-27', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-27', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-28', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-28', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-29', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-29', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '12pm', '2026-09-30', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '5pm', '2026-09-30', 10);

INSERT IGNORE INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-21', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-21', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-22', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-22', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-23', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-23', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-24', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-24', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-25', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-25', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-26', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-26', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-27', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-27', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-28', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-28', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-29', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-29', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '12pm', '2026-09-30', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '5pm', '2026-09-30', 10);

INSERT IGNORE INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-21', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-21', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-22', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-22', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-23', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-23', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-24', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-24', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-25', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-25', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-26', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-26', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-27', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-27', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-28', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-28', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-29', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-29', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '12pm', '2026-09-30', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '5pm', '2026-09-30', 10);

INSERT IGNORE INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-21', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-21', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-22', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-22', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-23', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-23', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-24', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-24', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-25', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-25', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-26', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-26', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-27', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-27', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-28', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-28', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-29', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-29', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '12pm', '2026-09-30', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '5pm', '2026-09-30', 10);

INSERT IGNORE INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-21', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-21', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-22', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-22', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-23', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-23', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-24', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-24', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-25', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-25', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-26', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-26', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-27', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-27', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-28', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-28', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-29', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-29', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '12pm', '2026-09-30', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '5pm', '2026-09-30', 10);