-- Seed data for the MovieShowing table
-- NOTE: table/column names below assume Spring Boot's default
-- camelCase-to-snake_case naming (MovieShowing -> movie_showing,
-- movieTitle -> movie_title). Verify with DESCRIBE MovieShowing;
-- before running this, and adjust the names below if they differ.

INSERT INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-03', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-03', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-04', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-04', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-05', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-05', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-06', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-06', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-07', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-07', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-08', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-08', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-09', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-09', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-10', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-10', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-11', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-11', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-12', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-12', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-13', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-13', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-14', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-14', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-15', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-15', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-16', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-16', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-17', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-17', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-18', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-18', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-19', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-19', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-20', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-20', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-21', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-21', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '8am', '2026-09-22', 10),
    ('Inception', 'Sci-Fi', 'A thief who steals corporate secrets through dream-sharing technology.', 148, '10am', '2026-09-22', 10);

INSERT INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-03', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-03', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-04', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-04', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-05', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-05', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-06', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-06', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-07', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-07', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-08', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-08', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-09', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-09', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-10', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-10', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-11', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-11', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-12', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-12', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-13', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-13', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-14', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-14', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-15', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-15', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-16', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-16', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-17', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-17', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-18', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-18', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-19', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-19', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-20', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-20', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-21', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-21', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '8am', '2026-09-22', 10),
    ('Dune', 'Sci-Fi', 'A noble family becomes embroiled in a war for control over a desert planet.', 155, '10am', '2026-09-22', 10);

INSERT INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-03', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-03', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-04', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-04', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-05', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-05', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-06', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-06', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-07', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-07', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-08', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-08', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-09', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-09', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-10', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-10', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-11', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-11', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-12', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-12', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-13', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-13', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-14', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-14', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-15', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-15', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-16', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-16', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-17', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-17', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-18', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-18', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-19', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-19', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-20', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-20', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-21', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-21', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '8am', '2026-09-22', 10),
    ('The Grand Budapest Hotel', 'Comedy', 'The adventures of a legendary concierge and his protege at a famous European hotel.', 99, '10am', '2026-09-22', 10);

INSERT INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-03', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-03', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-04', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-04', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-05', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-05', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-06', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-06', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-07', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-07', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-08', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-08', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-09', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-09', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-10', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-10', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-11', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-11', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-12', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-12', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-13', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-13', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-14', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-14', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-15', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-15', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-16', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-16', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-17', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-17', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-18', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-18', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-19', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-19', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-20', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-20', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-21', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-21', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '8am', '2026-09-22', 10),
    ('Parasite', 'Thriller', 'Greed and class discrimination threaten a newly formed symbiotic relationship between two families.', 132, '10am', '2026-09-22', 10);

INSERT INTO movie_showing (movie_title, genre, description, runtime, time, date, seats) VALUES
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-03', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-03', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-04', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-04', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-05', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-05', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-06', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-06', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-07', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-07', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-08', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-08', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-09', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-09', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-10', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-10', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-11', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-11', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-12', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-12', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-13', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-13', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-14', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-14', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-15', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-15', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-16', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-16', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-17', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-17', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-18', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-18', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-19', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-19', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-20', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-20', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-21', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-21', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '8am', '2026-09-22', 10),
    ('Whiplash', 'Drama', 'A young drummer enrolls at a cutthroat music conservatory under a demanding instructor.', 106, '10am', '2026-09-22', 10);